### ISSUE TITLE
pca9685 does not set fully on and fully off correctly

### ISSUE THREAD

**Issue by Ranthalion** [reef-pi/drivers#18]
According to the datasheet bit 4 in LEDn_ON_H and LEDn_OFF_H are special control bits to handle fully on and fully off.  reef-pi currently seems to turn turn off the pwm output when set to 100% based on https://www.reef2reef.com/threads/reef-pi-build-help.563754/

**Comment by ranjib** [comment]
https://github.com/sergiorb/pca9685-golang/blob/master/device/pca9685.go
