### ISSUE TITLE
Digital Loggers driver doesn't send all required data in HTTP PUT

### ISSUE THREAD

**Issue by dmolavi** [reef-pi/drivers#86]
In a nutshell, even though the code looks like it includes the 'www-form-urlencoded' header, it doesn't appear to. See the attached screenshot. I've attached 2 screenshots - one of a bad PUT (from reef-pi) and another with a good one, from PostMan. Note how the request is different
![Screenshot from 2021-12-07 19-17-55](https://user-images.githubusercontent.com/89136/145125970-8730cfac-5843-4ae4-a630-f778215422b8.png)
![Good_Request](https://user-images.githubusercontent.com/89136/145125972-ccf5450e-a1e9-4117-a5ad-f6231fb05b27.png)
.

**Comment by dmolavi** [comment]
On further inspection, reef-pi does send the www-form-urlencoded attribute, BUT in the authentication portion (which is redacted in my above screenshot), there is a difference. 
Reef-pi sends:
Authorization: Digest username="<myuser>", realm="<this matches>", **_nonce="",_** uri="/restapi/relay/outlets/1/state/", **_cnonce="<value>=", nc=value, qop=auth,_** response="<value>", _**opaque="",**_ algorithm="MD5"

The working request sends:
Authorization: Digest username="<myuser>", realm="<this matches>", _**nonce="<value>"**_, uri="/restapi/relay/outlets/1/state/", algorithm="MD5", response="<value>", **_opaque="<value>"_**
 
You can see where they differ...I can email you the captures directly if you'd like.

**Comment by ranjib** [comment]
these values are set from infering the dli response https://github.com/reef-pi/drivers/blob/master/dli/config.go
its still not clear why its failing though

**Comment by dmolavi** [comment]
[dli_fix.txt](https://github.com/reef-pi/drivers/files/7748803/dli_fix.txt)
 Patch file attached. This should fix it. Works on my DLI switch.

**Comment by ranjib** [comment]
@dmolavi https://github.com/reef-pi/drivers/pull/87
